### ISSUE TITLE
S0ix on stock kernel

### ISSUE THREAD

**Issue by andihoff98** [kitakar5525/note-linux-on-surface-3#1]
I am trying to achive low power sleep states on a Surface 3 with a stock 5.3.7 Arch kernel. If I read your notes correctly S0ix should work in stock kernel since 4.20 but I have a hard time replicating it. Are there any extra steps needed or did I misunderstood your notes?

**Comment by kitakar5525** [comment]
You may need to unload mwifiex modules before suspend like the [system-sleep/sleep](https://github.com/qzed/linux-surface/blob/master/root/lib/systemd/system-sleep/sleep) script from linux-surface repository.

Or have a look at kernel patch for mwifiex module in development:
- https://github.com/jakeday/linux-surface/issues/420#issuecomment-544615371

I'll look into S0ix states on stock Arch kernel later.

---

I use mainly Chromium OS on Surface 3 with my kernel (https://github.com/kitakar5525/chromeos-kernel-linux-surface) these days plus that patch and S0ix states are achieved stably without unloading mwifiex modules. (There are other issues on the kernel with suspend, though)

**Comment by kitakar5525** [comment]
S0ix states are working on my Surface 3 with the stock Arch kernel (`5.3.7-arch1-2-ARCH`) without unloading any modules before suspend.

As mentioned before, I think mwifiex modules might be the cause of S0ix failure on your device.

Another possibility is that, if you use TLP, make sure the config is the latest version. Specifically, make sure ASPM settings is set to `default` or `powersupersave` (or commented out) for both AC and BAT.

Link to the TLP config (ASPM lines):
https://github.com/linrunner/TLP/blob/1fc613d709c86821bb65d6b6048ff358b8a1a728/default#L182-L187

**Comment by kitakar5525** [comment]
If you still have trouble getting S0ix working on stock kernel, let me know and feel free to reopen this issue :)
