### ISSUE TITLE
Touchscreen Problem

### ISSUE THREAD

**Issue by orychalk** [kitakar5525/note-linux-on-surface-3#2]
Hello,

Great work :)

I see you have problem with touchscreen, and I just want to inform you that I use daily a Manjaro on my Surface3, and the only one kernel which is stable with touchscreen is :  Linux version 5.1.15-surface-linux-surface (jake@jake-Surface-Laptop)

Maybe you should already know it, but in case not  ;)

I had testing a lot of Kernel (from jakeday and others), but only this one work really good.

I found it in AUR (With Octopi) :
https://aur.archlinux.org/packages/linux-surface-jakeday-bin/

The touchscreen work at start, durably, and after hibernation.
The only thing who don't work with this kernel is the backlight and the shutdown/reboot after exit from hibernation.

I'm not developer, but maybe you can understand why it's work with this kernel and not with yours.

Have a good day.

**Comment by orychalk** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/57261547/68031811-ad1e3500-fcbc-11e9-9ab2-32bf623db597.png">

**Comment by kitakar5525** [comment]
Thank you for letting me know! I'll try the kernel later.

@ everyone
See also: jakeday/linux-surface#596

**Comment by kitakar5525** [comment]
Closing this issue as
- workaround (not desirable yet) merged as linux-surface/kernel@6c196de (v5.3), linux-surface/kernel@ccb08bd (v4.19) and linux-surface/kernel@66c8401 (v5.4)
- prebuilt kernel released (v5.3.18-1, v4.19.91-1, v5.4.6-1) (https://github.com/linux-surface/linux-surface/releases)
- received feedback that touch input is now working (on jakeday/linux-surface#596)

Thank you for your info and feedback!
